# Generated by Django 4.2.2 on 2023-08-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHive', '0002_factura_pago_remove_pagos_alumno_remove_pagos_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='parametrossar',
            name='RangoFinal',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='parametrossar',
            name='RangoInicial',
            field=models.CharField(max_length=8),
        ),
    ]
